pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    echo 'Compilando y ejecutando el programa Java...'
                    sh 'javac ./src/main/ControlCalidadEmpleados.java'
                    sh 'java ControlCalidadEmpleados'
                }
            }
        }
    }
}
