pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    echo 'Compiling and running ControlCalidadEmpleados.java'
                    sh 'javac ControlCalidadEmpleados.java'
                    sh 'java ControlCalidadEmpleados'
                }
            }
        }
    }
}
