pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    echo 'Compiling and running ControlCalidadEmpleados.java'
                    sh 'javac ./src/main/ControlCalidadEmpleados.java'
                    sh 'java ./src/main/ControlCalidadEmpleados'
                    def output = sh(script: 'java TuProgramaJava', returnStdout: true).trim()
                    echo "Salida del programa: ${output}"
                }
            }
        }
    }
}
