pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    echo 'Compilando y ejecutando el programa Java...'
                    sh 'echo $PATH'  // Imprime las rutas en Jenkins
                    sh 'which java'  // Encuentra la ubicación del ejecutable de Java

                   
                }
            }
        }
    }
}
