pipeline {
    agent any

    stages {
        stage('Build and Run') {
            steps {
                script {
                    echo 'Compilando y ejecutando el programa Java...'
                    sh '"C:\\Program Files\\Java\\jdk1.8.0_291\\bin\\javac" ControlCalidadEmpleados.java'
                    sh '"C:\\Program Files\\Java\\jdk1.8.0_291\\bin\\java" ControlCalidadEmpleados'
                }
            }
        }
    }
}
